apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`vault.allairis.com`)
      priority: 10
      services:
        - name: vault
          port: 80
  tls:
    certResolver: default
