metal:
  children:
    masters:
      hosts:
        metal0: { ansible_host: 192.168.2.200, mac: "00:23:24:d1:f3:f0", disk: sda, network_interface: enp4s0 }
        # metal1: { ansible_host: 192.168.2.201, mac: "00:23:24:d1:f4:d6", disk: sda, network_interface: enp4s0 }
        # metal2: { ansible_host: 192.168.2.202, mac: "00:23:24:e7:04:60", disk: sda, network_interface: enp4s0 }
    workers:
      hosts:
        {}
        # metal3: { ansible_host: 192.168.2.210, mac: "00:23:24:d1:f5:69", disk: sda, network_interface: enp4s0 }
